FROM jenkins/jenkins:lts

# Switch to root user to perform installations
USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io

# Check if docker group already exists, if not create it
RUN getent group docker || groupadd -g 999 docker && \
    usermod -aG docker jenkins

# Ensure tini is installed
RUN apt-get install -y tini

# Switch back to Jenkins user
USER jenkins

# Start Jenkins
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
